#################################################
# SPELL DEFINITION FILE
#################################################

# ATTACK SPELLS 

[SPELL]
<SPHERE>:ATTACK
<NAME>:Slow
<TARGET_ALIGNMENT>:EVIL
<TARGET>:CHARACTER
<CAST_TIME>:1
<MANA>:10
<ICON>:ICONS/spellslow.png:ICONS/spellslowa.png
<DESCRIPTION>:Slows target to 60%\nspeed for 10 seconds\n+1 seconds of duration per Attack Skill level

[EFFECT]
<NAME>:SLOW
<EXCLUSIVE>:1
<MESSAGE>:Slowed!
<ACTIVATION>:USAGE
<TYPE>:PERCENTSPEED
<DURATION>:10
<VALUE>:-40
<DURATION_BONUS>:1
[/EFFECT]

[EFFECT]
<NAME>:SLOWATTACK
<EXCLUSIVE>:1
<ACTIVATION>:USAGE
<TYPE>:PERCENTATTACKSPEED
<DURATION>:10
<VALUE>:-40
<DURATION_BONUS>:1
[/EFFECT]

#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:FOLLOWTARGET:10:1:0:0:SPELLS/EFFECTS/STAMINA/slow.mdl:1:1
<SFX>:FOLLOWTARGET:.5:1:0:0:SPELLS/EFFECTS/FIREPUFF/purplepuff.mdl:0:0
<SFX_DURATION_BONUS>:1
<SOUND>:SUCCESS:SOUNDS/SPELLS/slow.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast2.wav
<CAST_PARTICLE>:PURPLEFIRESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:10
[/SPELL]

[SPELL]
<SPHERE>:ATTACK
<NAME>:Fireball
<TARGET_ALIGNMENT>:EVIL
<TARGET>:PROJECTILE
<CAST_TIME>:1
<MANA>:12
<ICON>:ICONS/spellfireball.png:ICONS/spellfireballa.png
<DESCRIPTION>:Fireball flies straight, inflicting damage on impact\nfor 2-7 damage.\n+2 points of damage per Attack Skill level

[PAYLOADEFFECT]
<ACTIVATION>:USAGE
<TYPE>:HPRECHARGE
<DURATION>:INSTANT
<VALUE>:-2
<VALUE2>:-7
<VALUE_BONUS>:-2
<VALUE2_BONUS>:-2
<DAMAGE_TYPE>:FIRE
<SFX>:FOLLOWOWNER:.5:1:0:0:SPELLS/EFFECTS/FIREPUFF/firepuff.mdl:0:0
[/PAYLOADEFFECT]

#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:PROJECTILECHARACTER:2:1:35:0:SPELLS/EFFECTS/FIREBALL/fireball.mdl:0:1
<SOUND>:SUCCESS:SOUNDS/BATTLE/firehit.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast4.wav
<SOUND>:STRIKE:SOUNDS/FX/explode2.wav
<CAST_PARTICLE>:SPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:15
[/SPELL]

[SPELL]
<SPHERE>:ATTACK
<NAME>:Frost
<TARGET_ALIGNMENT>:EVIL
<TARGET>:PROJECTILE
<CAST_TIME>:1
<MANA>:15
<ICON>:ICONS/spellfrost.png:ICONS/spellfrosta.png
<DESCRIPTION>:Two icy blasts seek target,\ninflicting 3-4 damage on impact.\n+3 points of max damage per Attack Skill level\nAdditionally slows target by 40% for 5 seconds

[PAYLOADEFFECT]
<NAME>:SLOW
<EXCLUSIVE>:1
<MESSAGE>:Frozen!
<ACTIVATION>:USAGE
<TYPE>:PERCENTSPEED
<DURATION>:5
<VALUE>:-40
<SFX>:FOLLOWOWNER:5:1:0:0:SPELLS/EFFECTS/ICEPUFF/icepuff.ams:1:0
[/PAYLOADEFFECT]

[PAYLOADEFFECT]
<NAME>:SLOWATTACK
<EXCLUSIVE>:1
<ACTIVATION>:USAGE
<TYPE>:PERCENTATTACKSPEED
<DURATION>:5
<VALUE>:-40
[/PAYLOADEFFECT]

[PAYLOADEFFECT]
<ACTIVATION>:USAGE
<TYPE>:HPRECHARGE
<DURATION>:INSTANT
<VALUE>:-3
<VALUE2>:-5
<VALUE_BONUS>:0
<VALUE2_BONUS>:-3
<DAMAGE_TYPE>:ICE
[/PAYLOADEFFECT]

#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:PROJECTILECHARACTERERRATIC:3:1:20:2:SPELLS/EFFECTS/ICEBALL/iceball.mdl:0:1
<SFX>:PROJECTILECHARACTERERRATIC:3:1:20:2:SPELLS/EFFECTS/ICEBALL/iceball.mdl:0:1
<SOUND>:SUCCESS:SOUNDS/SPELLS/iceshot.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast3.wav
<SOUND>:STRIKE:SOUNDS/SPELLS/iceform.wav
<CAST_PARTICLE>:BLUESPARK:0:0:0
<CAST_PARTICLE>:SNOWFLAKE:0:0:0
<REQUIRES>:MAGIC:18
[/SPELL]

[SPELL]
<SPHERE>:ATTACK
<NAME>:Lightning Strike
<TARGET_ALIGNMENT>:EVIL
<TARGET>:CHARACTER
<CAST_TIME>:1
<MANA>:20
<ICON>:ICONS/spelllightning.png:ICONS/spelllightninga.png
<DESCRIPTION>:Lightning strikes target for\n8-10 damage.\n+4 points of max damage per Attack Skill level

[EFFECT]
<ACTIVATION>:USAGE
<TYPE>:HPRECHARGE
<DURATION>:INSTANT
<VALUE>:-8
<VALUE2>:-10
<VALUE_BONUS>:-0
<VALUE2_BONUS>:-4
<DAMAGE_TYPE>:ELECTRIC
[/EFFECT]

#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:STATIONARYTARGET:.5:1:0:0:SPELLS/EFFECTS/FIREPUFF/bluepuff.mdl:0:0
<SFX>:STATIONARYTARGET:-1:0:0:0:SPELLS/EFFECTS/LIGHTNING/lightning.ams:0:0
<SOUND>:SUCCESS:SOUNDS/SPELLS/lightning.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast2.wav
<CAST_PARTICLE>:ELECTRIC:0:0:0
<CAST_PARTICLE>:PURPLEFIRESPARK:0:0:0
<REQUIRES>:MAGIC:19
[/SPELL]

[SPELL]
<SPHERE>:ATTACK
<NAME>:Scorch
<TARGET_ALIGNMENT>:EVIL
<TARGET>:CHARACTER
<CAST_TIME>:1
<MANA>:23
<ICON>:ICONS/spellscorch.png:ICONS/spellscorcha.png
<DESCRIPTION>:Pillar of flame strikes target for\n7-12 damage.\n+1 point of min damage\nand +3 points of max damage per Attack Skill level

[EFFECT]
<ACTIVATION>:USAGE
<TYPE>:HPRECHARGE
<DURATION>:INSTANT
<VALUE>:-7
<VALUE2>:-12
<VALUE_BONUS>:-1
<VALUE2_BONUS>:-3
<DAMAGE_TYPE>:FIRE
[/EFFECT]

#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:STATIONARYTARGET:.5:1:0:0:EFFECTS/EXPLOSION/explosion.ams:0:0
<SFX>:STATIONARYTARGET:-1:0:0:0:SPELLS/EFFECTS/SCORCH/scorch.ams:0:0
<SOUND>:SUCCESS:SOUNDS/SPELLS/scorch.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast2.wav
<CAST_PARTICLE>:SMALLFIRE:0:0:0
<CAST_PARTICLE>:FIRESPARK:0:0:0
<REQUIRES>:MAGIC:23
[/SPELL]

[SPELL]
<SPHERE>:ATTACK
<NAME>:Muffle Magic
<TARGET_ALIGNMENT>:EVIL
<TARGET>:CHARACTER
<CAST_TIME>:1
<MANA>:40
<ICON>:ICONS/spellmufflemagic.png:ICONS/spellmufflemagica.png
<DESCRIPTION>:60% chance of preventing target from casting spells for 10 seconds\n+1 seconds of duration per Attack Skill level

[EFFECT]
<CHANCE_OF_SUCCESS>:60
<NAME>:MUFFLE
<EXCLUSIVE>:1
<MESSAGE>:Muffled!
<ACTIVATION>:USAGE
<TYPE>:PERCENTMANA
<DURATION>:10
<VALUE>:-500
<DURATION_BONUS>:1
<SFX>:FOLLOWTARGET:10:1:0:0:SPELLS/EFFECTS/MUFFLE/muffle.mdl:1:1
<SFX>:FOLLOWTARGET:.5:1:0:0:SPELLS/EFFECTS/FIREPUFF/greenpuff.mdl:0:0
<SFX_DURATION_BONUS>:1
[/EFFECT]


#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES
<SOUND>:SUCCESS:SOUNDS/SPELLS/muffle.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast5.wav
<CAST_PARTICLE>:PURPLEFIRESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:23
[/SPELL]

[SPELL]
<SPHERE>:ATTACK
<NAME>:Web
<TARGET_ALIGNMENT>:EVIL
<TARGET>:USERAREA
<RANGE>:15
<CAST_TIME>:2
<MANA>:42
<ICON>:ICONS/spellweb.png:ICONS/spellweba.png
<DESCRIPTION>:70% chance of binding creatures within 15 feet\nin sticky webbing, rendering them immobile\nfor 4 seconds. + 1 seconds per Attack Skill level

[EFFECT]
<NAME>:WEB
<EXCLUSIVE>:1
<CHANCE_OF_SUCCESS>:70
<ACTIVATION>:USAGE
<TYPE>:PERCENTSPEED
<MESSAGE>:Webbed!
<ACTIVATION>:USAGE
<DURATION>:4
<VALUE>:-100
<DURATION_BONUS>:1
<SFX>:FOLLOWOWNER:4:1:0:0:SPELLS/EFFECTS/WEB/web.ams:1:1
<SFX_DURATION_BONUS>:1
[/EFFECT]


#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:STATIONARYOWNER:-1:0:0:0:SPELLS/EFFECTS/RINGS/webring.ams:0:1
<SOUND>:SUCCESS:SOUNDS/SPELLS/web.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast6.wav
<CAST_PARTICLE>:SPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:25
[/SPELL]

[SPELL]
<SPHERE>:ATTACK
<NAME>:Blindness
<TARGET_ALIGNMENT>:EVIL
<TARGET>:CHARACTER
<CAST_TIME>:1
<MANA>:30
<ICON>:ICONS/spellblindness.png:ICONS/spellblindnessa.png
<DESCRIPTION>:Reduce target's Attack Rating by 75%\nfor 10 seconds +1 seconds of duration per Attack Skill level

[EFFECT]
<NAME>:BLIND
<EXCLUSIVE>:1
<MESSAGE>:Blind!
<ACTIVATION>:USAGE
<TYPE>:PERCENTTOHITBONUS
<DURATION>:10
<VALUE>:-75
<DURATION_BONUS>:1
<SFX>:FOLLOWTARGET:10:1:0:0:SPELLS/EFFECTS/blindness.mdl:1:1
<SFX>:FOLLOWTARGET:.5:1:0:0:SPELLS/EFFECTS/FIREPUFF/purplepuff.mdl:0:0
<SFX_DURATION_BONUS>:1
[/EFFECT]


#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES
<SOUND>:SUCCESS:SOUNDS/SPELLS/muffle.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast5.wav
<CAST_PARTICLE>:BLACKFIRESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:27
[/SPELL]

[SPELL]
<SPHERE>:ATTACK
<NAME>:Divine Light
<TARGET_ALIGNMENT>:EVIL
<TARGET>:USERAREA
<RANGE>:20
<CAST_TIME>:2
<MANA>:50
<ICON>:ICONS/spelldivine.png:ICONS/spelldivinea.png
<DESCRIPTION>:Cause 6-10 damage to undead targets\nwithin a 20 foot radius\n+2 points per Attack Skill level\nAdditional 50% chance that undead targets below level 20 will flee

[EFFECT]
<ACTIVATION>:USAGE
<TYPE>:HPRECHARGE
<DURATION>:INSTANT
<VALUE>:-6
<VALUE2>:-10
<VALUE_BONUS>:-2
<VALUE2_BONUS>:-2
<DAMAGE_TYPE>:UNDEAD
<SFX>:FOLLOWOWNER:.5:1:0:0:SPELLS/EFFECTS/FIREPUFF/firepuff.mdl:0:0
[/EFFECT]

[EFFECT]
<CHANCE_OF_SUCCESS>:50
<ACTIVATION>:USAGE
<TYPE>:FLEE
<VALUE>:20
<DURATION>:INSTANT
<DAMAGE_TYPE>:UNDEAD
[/EFFECT]

#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:STATIONARYOWNER:-1:0:0:0:SPELLS/EFFECTS/RINGS/holyring.ams:0:0
<SFX_DURATION_BONUS>:2
<SOUND>:SUCCESS:SOUNDS/SPELLS/slowblast.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast2.wav
<CAST_PARTICLE>:PURPLEFIRESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:28
[/SPELL]

[SPELL]
<SPHERE>:ATTACK
<NAME>:Fire Wall
<TARGET_ALIGNMENT>:EVIL
<TARGET>:USERAREA
<RANGE>:20
<CAST_TIME>:1.5
<MANA>:40
<ICON>:ICONS/spellfirewall.png:ICONS/spellfirewalla.png
<DESCRIPTION>:Creates a ring of fire 40 feet wide\ndamaging enemies for 4-8 damage.\n+2 points of damage per Attack Skill level

[EFFECT]
<ACTIVATION>:USAGE
<TYPE>:HPRECHARGE
<DURATION>:INSTANT
<VALUE>:-4
<VALUE2>:-8
<VALUE_BONUS>:-2
<VALUE2_BONUS>:-2
<DAMAGE_TYPE>:FIRE
<SFX>:FOLLOWOWNER:.5:1:0:0:SPELLS/EFFECTS/FIREPUFF/firepuff.mdl:0:0
[/EFFECT]

#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:STATIONARYOWNER:-1:0:0:0:SPELLS/EFFECTS/FIREWALL/firewall.ams:0:0
<SOUND>:SUCCESS:SOUNDS/SPELLS/firewall.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast4.wav
<CAST_PARTICLE>:SPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:28
[/SPELL]


[SPELL]
<SPHERE>:ATTACK
<NAME>:Frailty
<TARGET_ALIGNMENT>:EVIL
<TARGET>:CHARACTER
<CAST_TIME>:1
<MANA>:38
<ICON>:ICONS/spellfrailty.png:ICONS/spellfrailtya.png
<DESCRIPTION>:Reduces target's Defense Rating by\n75% for 7 seconds\n+1 second of duration per Attack Skill level

[EFFECT]
<NAME>:FRAILTY
<EXCLUSIVE>:1
<MESSAGE>:Frailty!
<ACTIVATION>:USAGE
<TYPE>:PERCENTARMORBONUS
<DURATION>:7
<VALUE>:-75
<DURATION_BONUS>:1
[/EFFECT]
#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:FOLLOWTARGET:7:1:0:0:SPELLS/EFFECTS/RINGS/frailty.ams:1:1
<SFX>:FOLLOWTARGET:.5:1:0:0:SPELLS/EFFECTS/FIREPUFF/greenpuff.mdl:0:0
<SFX_DURATION_BONUS>:1
<SOUND>:SUCCESS:SOUNDS/SPELLS/slow.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast2.wav
<CAST_PARTICLE>:GREENFIRESPARK:0:0:0
<CAST_PARTICLE>:BLACKFIRESPARK:0:0:0
<REQUIRES>:MAGIC:29
[/SPELL]

[SPELL]
<SPHERE>:ATTACK
<NAME>:Area Slow
<TARGET_ALIGNMENT>:EVIL
<TARGET>:USERAREA
<RANGE>:20
<CAST_TIME>:2
<MANA>:30
<ICON>:ICONS/spellareaslow.png:ICONS/spellareaslowa.png
<DESCRIPTION>:90% chance of slowing targets in\na 20 foot radius to 60% speed\nfor 6 seconds +1 seconds of duration per Attack Skill level

[EFFECT]
<CHANCE_OF_SUCCESS>:90
<NAME>:SLOW
<EXCLUSIVE>:1
<MESSAGE>:Slowed!
<ACTIVATION>:USAGE
<TYPE>:PERCENTSPEED
<DURATION>:6
<VALUE>:-40
<DURATION_BONUS>:1
<SFX>:FOLLOWTARGET:6:1:0:0:SPELLS/EFFECTS/STAMINA/slow.mdl:1:1
<SFX>:FOLLOWTARGET:.5:1:0:0:SPELLS/EFFECTS/FIREPUFF/purplepuff.mdl:0:0
<SFX_DURATION_BONUS>:1
[/EFFECT]

[EFFECT]
<CHANCE_OF_SUCCESS>:90
<NAME>:SLOWATTACK
<EXCLUSIVE>:1
<ACTIVATION>:USAGE
<TYPE>:PERCENTATTACKSPEED
<DURATION>:6
<VALUE>:-40
<DURATION_BONUS>:1
[/EFFECT]
#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:STATIONARYOWNER:-1:0:0:0:SPELLS/EFFECTS/PURPLEBLAST/blast.ams:0:0
<SFX_DURATION_BONUS>:2
<SOUND>:SUCCESS:SOUNDS/SPELLS/slowblast.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast2.wav
<CAST_PARTICLE>:PURPLEFIRESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:30
[/SPELL]

[SPELL]
<SPHERE>:ATTACK
<NAME>:Poison Cloud
<TARGET_ALIGNMENT>:EVIL
<TARGET>:AREA
<RANGE>:20
<CAST_TIME>:2
<MANA>:60
<ICON>:ICONS/spellpoison.png:ICONS/spellpoisona.png
<DESCRIPTION>:Poisons all hostile targets within 20 feet of target location.\nPoison duration is 20 seconds\n2 points of damage per second\n+2 seconds per Attack Skill level

[PAYLOADEFFECT]
<NAME>:POISON
<EXCLUSIVE>:1
<ACTIVATION>:USAGE
<TYPE>:HPRECHARGE
<DURATION>:20
<VALUE>:-120
<DURATION_BONUS>:2
<DAMAGE_TYPE>:MAGIC
<CHANCE_OF_SUCCESS>:100
<SFX>:STATIONARYOWNER:-1:0:0:0:EFFECTS/POISON/poison.ams:0:1
[/PAYLOADEFFECT]

#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:PROJECTILELOCATION:1.5:1:35:0:SPELLS/EFFECTS/POISONBALL/poisonball.mdl:0:1
<PAYLOADSFX>:STATIONARYTARGET:2:1:0:0:SPELLS/EFFECTS/POISONCLOUD/poisoncloud.mdl:0:1
<SOUND>:SUCCESS:SOUNDS/BATTLE/firehit.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast4.wav
<SOUND>:STRIKE:SOUNDS/FX/poison2.wav
<CAST_PARTICLE>:GREENFIRESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:38
[/SPELL]

[SPELL]
<SPHERE>:ATTACK
<NAME>:Draining Aura
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:3
<MANA>:65
<ICON>:ICONS/spelllifedrain.png:ICONS/spelllifedraina.png
<DESCRIPTION>:Steals 50% of all damage dealt to target\nand heals caster, but\ndrains stamina. Lasts for 10 seconds.\n+ 1 second per Attack Skill level.

[EFFECT]
<NAME>:DRAIN
<EXCLUSIVE>:1
<MESSAGE>:Draining Aura!
<ACTIVATION>:USAGE
<TYPE>:PERCENTLIFESTOLEN
<VALUE>:50
<DURATION>:10
<DURATION_BONUS>:1
[/EFFECT]

[EFFECT]
<NAME>:REFLECT
<EXCLUSIVE>:1
<ACTIVATION>:USAGE
<TYPE>:STAMINARECHARGE
<DURATION>:10
<VALUE>:-10000
<DURATION_BONUS>:1
[/EFFECT]

#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:FOLLOWTARGET:10:1:0:0:SPELLS/EFFECTS/STAMINA/lifesteal.mdl:1:1
<SFX>:FOLLOWTARGET:.5:1:0:0:SPELLS/EFFECTS/FIREPUFF/purplepuff.mdl:0:0
<SFX_DURATION_BONUS>:1
<SOUND>:SUCCESS:SOUNDS/SPELLS/charm.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast3.wav
<CAST_PARTICLE>:REDFIRESPARK:0:0:0
<CAST_PARTICLE>:PURPLEFIRESPARK:0:0:0
<REQUIRES>:MAGIC:42
[/SPELL]

[SPELL]
<SPHERE>:ATTACK
<NAME>:Lightning Storm
<TARGET_ALIGNMENT>:EVIL
<TARGET>:USERAREA
<RANGE>:20
<CAST_TIME>:2.0
<MANA>:70
<ICON>:ICONS/spellstorm.png:ICONS/spellstorma.png
<DESCRIPTION>:Calls forth a lightning storm\nwith 80% chance of damaging enemies in a 20 foot radius\nfor 10-15 damage.\n+5 points of max damage per Attack Skill level

[EFFECT]
<CHANCE_OF_SUCCESS>:80
<ACTIVATION>:USAGE
<TYPE>:HPRECHARGE
<DURATION>:INSTANT
<VALUE>:-10
<VALUE2>:-15
<VALUE_BONUS>:-0
<VALUE2_BONUS>:-5
<DAMAGE_TYPE>:ELECTRIC
<SFX>:FOLLOWOWNER:.5:1:0:0:SPELLS/EFFECTS/FIREPUFF/bluepuff.mdl:0:0
[/EFFECT]

#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:STATIONARYOWNER:-1:0:0:0:SPELLS/EFFECTS/LIGHTNINGSTORM/lightning.ams:0:0
<SFX>:STATIONARYOWNER:-1:0:0:0:SPELLS/EFFECTS/LIGHTNINGBLAST/blast.ams:0:1
<SOUND>:SUCCESS:SOUNDS/SPELLS/lightning.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast2.wav
<CAST_PARTICLE>:BIGELECTRIC:0:0:0
<CAST_PARTICLE>:PURPLEFIRESPARK:0:0:0
<CAST_PARTICLE>:BLACKFIRESPARK:0:0:0
<REQUIRES>:MAGIC:50
[/SPELL]


[SPELL]
<SPHERE>:ATTACK
<NAME>:Shocking Burst
<TARGET_ALIGNMENT>:EVIL
<TARGET>:AREA
<RANGE>:20
<CAST_TIME>:1
<MANA>:70
<ICON>:ICONS/spellshocking.png:ICONS/spellshockinga.png
<DESCRIPTION>:Seeking electrical projectile that shocks target\nand nearby targets for 6-10 damage.\n+1 point of min damage and\n+4 points of max damage per Attack Skill level

[PAYLOADEFFECT]
<ACTIVATION>:USAGE
<TYPE>:HPRECHARGE
<DURATION>:INSTANT
<VALUE>:-6
<VALUE2>:-10
<VALUE_BONUS>:-1
<VALUE2_BONUS>:-4
<DAMAGE_TYPE>:ELECTRIC
<SFX>:FOLLOWOWNER:.5:1:0:0:SPELLS/EFFECTS/FIREPUFF/electricpuff.mdl:0:0
[/PAYLOADEFFECT]

#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:PROJECTILECHARACTER:3:1:20:2:SPELLS/EFFECTS/LIGHTNINGSTORM/burstball.ams:0:1
<PAYLOADSFX>:STATIONARYTARGET:-1:0:0:0:SPELLS/EFFECTS/LIGHTNINGSTORM/lowlightning.ams:0:0
<PAYLOADSFX>:STATIONARYTARGET:-1:0:0:0:SPELLS/EFFECTS/LIGHTNINGBLAST/blast.ams:0:1
<SOUND>:SUCCESS:SOUNDS/BATTLE/firehit.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast2.wav
<SOUND>:STRIKE:SOUNDS/SPELLS/lightning.wav
<CAST_PARTICLE>:BIGELECTRIC:0:0:0
<CAST_PARTICLE>:PURPLEFIRESPARK:0:0:0
<CAST_PARTICLE>:BLACKFIRESPARK:0:0:0
<REQUIRES>:MAGIC:45
[/SPELL]

[SPELL]
<SPHERE>:ATTACK
<NAME>:Meteor Strike
<TARGET_ALIGNMENT>:EVIL
<TARGET>:AREA
<RANGE>:20
<CAST_TIME>:1
<MANA>:70
<ICON>:ICONS/spellmeteor.png:ICONS/spellmeteora.png
<DESCRIPTION>:Calls meteors from the sky at target location\nand damages nearby targets for 12-22 damage.\n+3 points of damage per Attack Skill level

[PAYLOADEFFECT]
<ACTIVATION>:USAGE
<TYPE>:HPRECHARGE
<DURATION>:INSTANT
<VALUE>:-12
<VALUE2>:-22
<VALUE_BONUS>:-3
<VALUE2_BONUS>:-3
<DAMAGE_TYPE>:FIRE
<SFX>:FOLLOWOWNER:.5:1:0:0:SPELLS/EFFECTS/FIREPUFF/firepuff.mdl:0:0
[/PAYLOADEFFECT]

#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:PROJECTILELOCATION:2:1:35:0:SPELLS/EFFECTS/FIREBALL/fireball.mdl:0:1
<PAYLOADSFX>:STATIONARYTARGET:-1:0:0:0:SPELLS/EFFECTS/FIREBALL/meteorstrike.ams:0:0
<PAYLOADSFX>:STATIONARYTARGET:-1:0:0:0:SPELLS/EFFECTS/FIREBLAST/blast.ams:0:1
<SOUND>:SUCCESS:SOUNDS/BATTLE/firehit.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast2.wav
<SOUND>:STRIKE:SOUNDS/SPELLS/firewall.wav
<CAST_PARTICLE>:FIRE:0:0:0
<CAST_PARTICLE>:SPELLFIRESPARK:0:0:0
<REQUIRES>:MAGIC:55
[/SPELL]


# CHARM SPELLS 

[SPELL]
<SPHERE>:CHARM
<NAME>:Identify
<TARGET_ALIGNMENT>:ALL
<TARGET>:ITEM
<CAST_TIME>:0
<MANA>:10
<ICON>:ICONS/spellidentify.png:ICONS/spellidentifya.png
<DESCRIPTION>:Identifies an item of\nlevel 3 and below\nIdentify level +3 per Charm Skill level

[EFFECT]
<ACTIVATION>:USAGE
<NAME>:IDENTIFY
<TYPE>:IDENTIFY
<DURATION>:INSTANT
<VALUE>:3
<VALUE_BONUS>:3
[/EFFECT]

<SOUND>:SUCCESS:SOUNDS/SPELLS/identify.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<REQUIRES>:MAGIC:10
[/SPELL]

[SPELL]
<SPHERE>:CHARM
<NAME>:Mental Map
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:3
<MANA>:20
<ICON>:ICONS/spelldiscover.png:ICONS/spelldiscovera.png
<DESCRIPTION>:Discovers all areas of a map\nof level 2 or above\nWorks at +2 levels deeper per Charm Skill level.

[EFFECT]
<ACTIVATION>:USAGE
<NAME>:DISCOVER
<TYPE>:DISCOVER
<DURATION>:INSTANT
<VALUE>:2
<VALUE_BONUS>:2
[/EFFECT]

<SOUND>:CHANT:SOUNDS/SPELLS/cast.wav
<SOUND>:SUCCESS:SOUNDS/SPELLS/reveal.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<CAST_PARTICLE>:greenfirespark:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:20
[/SPELL]

[SPELL]
<SPHERE>:CHARM
<NAME>:Town Portal
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:5
<MANA>:20
<ICON>:ICONS/spelltownportal.png:ICONS/spelltownportala.png
<DESCRIPTION>:Opens a portal to the town of Grove\non dungeon level 2 or above\nWorks at +2 levels deeper per Charm Skill level.

[EFFECT]
<ACTIVATION>:USAGE
<NAME>:OPENPORTAL
<TYPE>:OPENPORTAL
<DURATION>:INSTANT
<VALUE>:2
<VALUE_BONUS>:2
[/EFFECT]

<SOUND>:CHANT:SOUNDS/SPELLS/cast.wav
<SOUND>:SUCCESS:SOUNDS/SPELLS/reveal.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<CAST_PARTICLE>:greenfirespark:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:23
[/SPELL]

[SPELL]
<SPHERE>:CHARM
<NAME>:Summon Spiders
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:3
<MANA>:14
<ICON>:ICONS/spellspider.png:ICONS/spellspidera.png
<DESCRIPTION>:Summons 3 Level 1 spiders to aid caster\n+1 to spider's level per Charm Skill level\nDuration of summoning is 1 minute\n+10 seconds per Charm Skill Level\nMaximum of 6 summoned creatures

[EFFECT]
<NAME>:WIDOWLING
<ACTIVATION>:USAGE
<TYPE>:SUMMON
<DURATION>:INSTANT
<VALUE>:3
<VALUE2>:1
<VALUE2_BONUS>:1
<VALUE3>:60
<VALUE3_BONUS>:10
#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:FOLLOWTARGET:1:1:0:0:SPELLS/EFFECTS/DISPEL/dispel.mdl:0:0
[/EFFECT]

<SOUND>:SUCCESS:SOUNDS/SPELLS/heal.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast.wav
<CAST_PARTICLE>:greenfirespark:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:16
[/SPELL]

[SPELL]
<SPHERE>:CHARM
<NAME>:Summon Rats
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:3
<MANA>:20
<ICON>:ICONS/spellrat.png:ICONS/spellrata.png
<DESCRIPTION>:Summons 3 Level 1 rats to aid caster\n+1 to rat's level per Charm Skill level\nDuration of summoning is 1 minute\n+10 seconds per Charm Skill Level\nMaximum of 6 summoned creatures

[EFFECT]
<NAME>:SEWER RAT
<ACTIVATION>:USAGE
<TYPE>:SUMMON
<DURATION>:INSTANT
<VALUE>:3
<VALUE2>:1
<VALUE2_BONUS>:1
<VALUE3>:60
<VALUE3_BONUS>:10
#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:FOLLOWTARGET:1:1:0:0:SPELLS/EFFECTS/DISPEL/dispel.mdl:0:0
[/EFFECT]

<SOUND>:SUCCESS:SOUNDS/SPELLS/heal.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast.wav
<CAST_PARTICLE>:greenfirespark:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:18
[/SPELL]

[SPELL]
<SPHERE>:CHARM
<NAME>:Summon Skeleton
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:2
<MANA>:25
<ICON>:ICONS/spellskeleton.png:ICONS/spellskeletona.png
<DESCRIPTION>:Summons 1 level 4 Skeleton to aid caster\n+1 to Skeleton's level per Charm Skill level\nDuration of summoning is 1 minute\n+10 seconds per Charm Skill Level\nMaximum of 6 summoned creatures

[EFFECT]
<NAME>:SKELETON
<ACTIVATION>:USAGE
<TYPE>:SUMMON
<DURATION>:INSTANT
<VALUE>:1
<VALUE2>:4
<VALUE2_BONUS>:1
<VALUE3>:60
<VALUE3_BONUS>:10
#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:FOLLOWTARGET:1:1:0:0:SPELLS/EFFECTS/DISPEL/dispel.mdl:0:0
[/EFFECT]

<SOUND>:SUCCESS:SOUNDS/SPELLS/heal.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast.wav
<CAST_PARTICLE>:GREENFIRESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:22
[/SPELL]

[SPELL]
<SPHERE>:CHARM
<NAME>:Mystic Blade
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:2
<MANA>:30
<ICON>:ICONS/spellblade.png:ICONS/spellbladea.png
<DESCRIPTION>:Summons 1 level 7 Cursed Sword to aid caster\n+1 to Sword's level per 2 Charm Skill levels\nDuration of summoning is 1 minute\n+10 seconds per Charm Skill Level\nMaximum of 6 summoned creatures

[EFFECT]
<NAME>:CURSED SWORD
<ACTIVATION>:USAGE
<TYPE>:SUMMON
<DURATION>:INSTANT
<VALUE>:1
<VALUE2>:7
<VALUE2_BONUS>:.5
<VALUE3>:60
<VALUE3_BONUS>:10
#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:FOLLOWTARGET:1:1:0:0:SPELLS/EFFECTS/DISPEL/dispel.mdl:0:0
[/EFFECT]

<SOUND>:SUCCESS:SOUNDS/SPELLS/heal.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast.wav
<CAST_PARTICLE>:GREENFIRESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:30
[/SPELL]

[SPELL]
<SPHERE>:CHARM
<NAME>:Summon Vampire Bat
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:2
<MANA>:35
<ICON>:ICONS/spellbats.png:ICONS/spellbatsa.png
<DESCRIPTION>:Summons 3 level 10 Vampire Bats to aid caster\n+1 to Bats' level per 3 Charm Skill levels\nDuration of summoning is 1 minute\n+10 seconds per Charm Skill Level\nMaximum of 6 summoned creatures

[EFFECT]
<NAME>:VAMPIRE BAT
<ACTIVATION>:USAGE
<TYPE>:SUMMON
<DURATION>:INSTANT
<VALUE>:3
<VALUE2>:10
<VALUE2_BONUS>:.3333
<VALUE3>:60
<VALUE3_BONUS>:10
#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:FOLLOWTARGET:1:1:0:0:SPELLS/EFFECTS/DISPEL/dispel.mdl:0:0
[/EFFECT]

<SOUND>:SUCCESS:SOUNDS/SPELLS/heal.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast.wav
<CAST_PARTICLE>:GREENFIRESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:35
[/SPELL]

[SPELL]
<SPHERE>:CHARM
<NAME>:Summon Timberwolf
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:2
<MANA>:39
<ICON>:ICONS/spellwolf.png:ICONS/spellwolfa.png
<DESCRIPTION>:Summons 2 level 7 Timberwolves to aid caster\n+1 to Timberwolf's level per 2 Charm Skill levels\nDuration of summoning is 1 minute\n+10 seconds per Charm Skill Level\nMaximum of 6 summoned creatures

[EFFECT]
<NAME>:TIMBERWOLF
<ACTIVATION>:USAGE
<TYPE>:SUMMON
<DURATION>:INSTANT
<VALUE>:2
<VALUE2>:7
<VALUE2_BONUS>:.5
<VALUE3>:60
<VALUE3_BONUS>:10
#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:FOLLOWTARGET:1:1:0:0:SPELLS/EFFECTS/DISPEL/dispel.mdl:0:1
[/EFFECT]

<SOUND>:SUCCESS:SOUNDS/SPELLS/heal.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast.wav
<CAST_PARTICLE>:GREENFIRESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:39
[/SPELL]

[SPELL]
<SPHERE>:CHARM
<NAME>:Summon Frost Beetle
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:2
<MANA>:45
<ICON>:ICONS/spellbeetle.png:ICONS/spellbeetlea.png
<DESCRIPTION>:Summons 2 level 13 Frost Beetles to aid caster\n+1 to Beetles' level per 2 Charm Skill levels\nDuration of summoning is 1 minute\n+10 seconds per Charm Skill Level\nMaximum of 6 summoned creatures

[EFFECT]
<NAME>:FROST BEETLE
<ACTIVATION>:USAGE
<TYPE>:SUMMON
<DURATION>:INSTANT
<VALUE>:2
<VALUE2>:13
<VALUE2_BONUS>:.5
<VALUE3>:60
<VALUE3_BONUS>:10
#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:FOLLOWTARGET:1:1:0:0:SPELLS/EFFECTS/DISPEL/dispel.mdl:0:0
[/EFFECT]

<SOUND>:SUCCESS:SOUNDS/SPELLS/heal.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast.wav
<CAST_PARTICLE>:GREENFIRESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:46
[/SPELL]

[SPELL]
<SPHERE>:CHARM
<NAME>:Summon Shrike
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:2
<MANA>:50
<ICON>:ICONS/spellshrike.png:ICONS/spellshrikea.png
<DESCRIPTION>:Summons 1 level 14 Shrike to aid caster\n+1 to Shrike's level per 2 Charm Skill levels\nDuration of summoning is 1 minute\n+10 seconds per Charm Skill Level\nMaximum of 6 summoned creatures

[EFFECT]
<NAME>:SHRIKE
<ACTIVATION>:USAGE
<TYPE>:SUMMON
<DURATION>:INSTANT
<VALUE>:1
<VALUE2>:14
<VALUE2_BONUS>:.5
<VALUE3>:60
<VALUE3_BONUS>:10
#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:FOLLOWTARGET:1:1:0:0:SPELLS/EFFECTS/DISPEL/dispel.mdl:0:1
[/EFFECT]

<SOUND>:SUCCESS:SOUNDS/SPELLS/heal.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast.wav
<CAST_PARTICLE>:GREENFIRESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:55
[/SPELL]

[SPELL]
<SPHERE>:CHARM
<NAME>:Summon Wyvern
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:2
<MANA>:50
<ICON>:ICONS/spellwyvern.png:ICONS/spellwyverna.png
<DESCRIPTION>:Summons 1 level 28 Venomous Wyvern to aid caster\n+1 to Wyvern's level per 4 Charm Skill levels\nDuration of summoning is 1 minute\n+10 seconds per Charm Skill level\nMaximum of 6 summoned creatures

[EFFECT]
<NAME>:VENOMOUS WYVERN
<ACTIVATION>:USAGE
<TYPE>:SUMMON
<DURATION>:INSTANT
<VALUE>:1
<VALUE2>:28
<VALUE2_BONUS>:.25
<VALUE3>:60
<VALUE3_BONUS>:10
#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:FOLLOWTARGET:1:1:0:0:SPELLS/EFFECTS/DISPEL/dispel.mdl:0:1
[/EFFECT]

<SOUND>:SUCCESS:SOUNDS/SPELLS/heal.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast.wav
<CAST_PARTICLE>:GREENFIRESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:68
[/SPELL]

[SPELL]
<SPHERE>:CHARM
<NAME>:Summon Firedrake
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:2
<MANA>:80
<ICON>:ICONS/spellfiredrake.png:ICONS/spellfiredrakea.png
<DESCRIPTION>:Summons 1 level 28 Firedrake to aid caster\n+1 to Firedrake's level per 10 Charm Skill levels\nDuration of summoning is 40 seconds\n+5 seconds per Charm Skill Level\nMaximum of 6 summoned creatures

[EFFECT]
<NAME>:FIREDRAKE
<ACTIVATION>:USAGE
<TYPE>:SUMMON
<DURATION>:INSTANT
<VALUE>:1
<VALUE2>:28
<VALUE2_BONUS>:.1
<VALUE3>:40
<VALUE3_BONUS>:5
#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:FOLLOWTARGET:1:1:0:0:SPELLS/EFFECTS/DISPEL/dispel.mdl:0:1
[/EFFECT]

<SOUND>:SUCCESS:SOUNDS/SPELLS/heal.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast.wav
<CAST_PARTICLE>:GREENFIRESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:97
[/SPELL]

[SPELL]
<SPHERE>:CHARM
<NAME>:Charm Monster
<TARGET_ALIGNMENT>:EVIL
<TARGET>:CHARACTER
<CAST_TIME>:1
<MANA>:40
<ICON>:ICONS/spellcharm.png:ICONS/spellcharma.png
<DESCRIPTION>:Charm monster to fight for caster\nCharms monsters of level 6 and below for 20 seconds\n+2 creature levels per Charm Skill level

[EFFECT]
<NAME>:CHARM
<EXCLUSIVE>:1
<MESSAGE>:Charmed!
<ACTIVATION>:USAGE
<TYPE>:TURNALIGNMENT
<DURATION>:20
<VALUE>:6
<VALUE_BONUS>:2
<SFX>:FOLLOWTARGET:20:1:0:0:SPELLS/EFFECTS/STAMINA/charm.mdl:1:1
<SFX>:FOLLOWTARGET:.5:1:0:0:SPELLS/EFFECTS/FIREPUFF/greenpuff.mdl:0:0
[/EFFECT]


#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES
<SOUND>:SUCCESS:SOUNDS/SPELLS/muffle.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast5.wav
<CAST_PARTICLE>:GREENFIRESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:40
[/SPELL]

[SPELL]
<SPHERE>:CHARM
<NAME>:Dispel Summoned Monster
<TARGET_ALIGNMENT>:EVIL
<TARGET>:USER
<CAST_TIME>:1
<MANA>:10
<ICON>:ICONS/spelldispel.png:ICONS/spelldispela.png
<DESCRIPTION>:Dispel all creatures summoned by caster

[EFFECT]
<NAME>:DISPEL
<EXCLUSIVE>:1
<ACTIVATION>:USAGE
<TYPE>:DISPEL
[/EFFECT]


#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES
<SOUND>:SUCCESS:SOUNDS/SPELLS/muffle.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast5.wav
<CAST_PARTICLE>:GREENFIRESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:10
[/SPELL]


[SPELL]
<SPHERE>:DEFENSE
<NAME>:Stamina
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:2
<MANA>:20
<ICON>:ICONS/spellstamina.png:ICONS/spellstaminaa.png
<DESCRIPTION>:Recharges stamina\nlasts for 10 seconds\n+1 second of duration per Defense Skill level

[EFFECT]
<NAME>:REFLECT
<EXCLUSIVE>:1
<MESSAGE>:Stamina!
<ACTIVATION>:USAGE
<TYPE>:STAMINARECHARGE
<DURATION>:10
<VALUE>:200
<DURATION_BONUS>:1
[/EFFECT]

#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES
<SFX>:FOLLOWTARGET:10:1:0:0:SPELLS/EFFECTS/STAMINA/stamina.mdl:1:1
<SFX_DURATION_BONUS>:1
<SOUND>:SUCCESS:SOUNDS/SPELLS/charm.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast3.wav
<CAST_PARTICLE>:YELLOWSPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:10
[/SPELL]

[SPELL]
<SPHERE>:DEFENSE
<NAME>:Minor Heal
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:2
<MANA>:20
<ICON>:ICONS/spellheal.png:ICONS/spellheala.png
<DESCRIPTION>:Heals caster for 20 HP\n+2 HP per Defense Skill level

[EFFECT]
<ACTIVATION>:USAGE
<TYPE>:HPRECHARGE
<DURATION>:INSTANT
<VALUE>:20
<VALUE_BONUS>:2
[/EFFECT]

#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:FOLLOWTARGET:-1:0:0:0:SPELLS/EFFECTS/HEAL/heal.ams:0:1
<SOUND>:SUCCESS:SOUNDS/SPELLS/heal.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast.wav
<CAST_PARTICLE>:BLUESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0

<REQUIRES>:MAGIC:15
[/SPELL]

[SPELL]
<SPHERE>:DEFENSE
<NAME>:Spectral Armor
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:2
<MANA>:32
<ICON>:ICONS/spellarmor.png:ICONS/spellarmora.png
<DESCRIPTION>:Increases defense rating by 40 +4 per Defense Skill level\nReduces damage by 25%\nlasts for 20 seconds\n+1 seconds of duration per Defense Skill level

[EFFECT]
<NAME>:ARMOR
<EXCLUSIVE>:1
<MESSAGE>:Spectral Armor!
<ACTIVATION>:USAGE
<TYPE>:PERCENTDAMAGETAKEN
<DURATION>:20
<VALUE>:-25
<DURATION_BONUS>:1
[/EFFECT]

[EFFECT]
<NAME>:ARMORBONUS
<EXCLUSIVE>:1
<ACTIVATION>:USAGE
<TYPE>:ARMORBONUS
<DURATION>:20
<VALUE>:40
<VALUE_BONUS>:4
<DURATION_BONUS>:1
[/EFFECT]

#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:STATIONARYTARGET:-1:0:0:0:SPELLS/EFFECTS/HASTE/haste.ams:0:1
<SFX>:FOLLOWTARGET:20:1:0:0:SPELLS/EFFECTS/ARMOR/armor.sms:1:1
<SFX_DURATION_BONUS>:1
<SOUND>:SUCCESS:SOUNDS/SPELLS/charm.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast3.wav
<CAST_PARTICLE>:BLUESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:18
[/SPELL]

[SPELL]
<SPHERE>:DEFENSE
<NAME>:Minor Group Heal
<TARGET_ALIGNMENT>:ALL
<TARGET>:USERANDPETS
<CAST_TIME>:3
<MANA>:25
<ICON>:ICONS/spellgroupheal.png:ICONS/spellgroupheala.png
<DESCRIPTION>:Heals caster and minions for 10 HP\n+2 HP per Defense Skill level

[EFFECT]
<ACTIVATION>:USAGE
<TYPE>:HPRECHARGE
<DURATION>:INSTANT
<VALUE>:10
<VALUE_BONUS>:2
[/EFFECT]

#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:FOLLOWTARGET:-1:0:0:0:SPELLS/EFFECTS/HEAL/heal.ams:0:1
<SOUND>:SUCCESS:SOUNDS/SPELLS/heal.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast.wav
<CAST_PARTICLE>:BLUESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:19
[/SPELL]

[SPELL]
<SPHERE>:DEFENSE
<NAME>:Ringing Blast
<TARGET_ALIGNMENT>:EVIL
<TARGET>:USERAREA
<RANGE>:25
<CAST_TIME>:2
<MANA>:18
<ICON>:ICONS/spellblast.png:ICONS/spellblasta.png
<DESCRIPTION>:Creates a blast of air 40 feet wide\nknocking back enemies for 1-2 damage.\n+2 points of damage per Defense Skill level

[EFFECT]
<ACTIVATION>:USAGE
<TYPE>:HPRECHARGE
<DURATION>:INSTANT
<VALUE>:-1
<VALUE2>:-2
<VALUE_BONUS>:-1
<VALUE2_BONUS>:-2
<DAMAGE_TYPE>:MAGIC
[/EFFECT]

[EFFECT]
<NAME>:KNOCKBACK
<ACTIVATION>:USAGE
<TYPE>:KNOCKBACKEFFECT
<DURATION>:12
<VALUE>:6
[/EFFECT]

#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:STATIONARYOWNER:-1:0:0:0:SPELLS/EFFECTS/BLAST/blast.ams:0:1
<SOUND>:SUCCESS:SOUNDS/SPELLS/firewall.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast4.wav
<CAST_PARTICLE>:BLUESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:20
[/SPELL]

[SPELL]
<SPHERE>:DEFENSE
<NAME>:Haste
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:3
<MANA>:30
<ICON>:ICONS/spellhaste.png:ICONS/spellhastea.png
<DESCRIPTION>:Speeds up caster by 1/3\nspeed for 15 seconds\n+1 second of duration per Defense Skill level

[EFFECT]
<NAME>:HASTEATTACK
<EXCLUSIVE>:1
<ACTIVATION>:USAGE
<TYPE>:PERCENTATTACKSPEED
<DURATION>:15
<VALUE>:33
<DURATION_BONUS>:1
[/EFFECT]

[EFFECT]
<NAME>:HASTE
<EXCLUSIVE>:1
<MESSAGE>:Haste!
<ACTIVATION>:USAGE
<TYPE>:PERCENTSPEED
<DURATION>:15
<VALUE>:33
<DURATION_BONUS>:1
[/EFFECT]

#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

#<SFX>:STATIONARYTARGET:-1:0:0:0:SPELLS/EFFECTS/HASTE/haste.ams:0:1
<SFX>:FOLLOWTARGET:15:1:0:0:SPELLS/EFFECTS/RINGS/bluering.ams:1:1
<SFX>:FOLLOWTARGET:.5:1:0:0:SPELLS/EFFECTS/FIREPUFF/purplepuff.mdl:0:0
<SFX_DURATION_BONUS>:1
<SOUND>:SUCCESS:SOUNDS/SPELLS/charm.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast3.wav
<CAST_PARTICLE>:PURPLEFIRESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:21
[/SPELL]

[SPELL]
<SPHERE>:DEFENSE
<NAME>:Reflection
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:2
<MANA>:40
<ICON>:ICONS/spellreflect.png:ICONS/spellreflecta.png
<DESCRIPTION>:Reflects 20% of damage to attacker\nlasts for 10 seconds\n+2 seconds of duration per Defense Skill level

[EFFECT]
<NAME>:REFLECT
<EXCLUSIVE>:1
<MESSAGE>:Reflection!
<ACTIVATION>:USAGE
<TYPE>:PERCENTDAMAGEREFLECTED
<DURATION>:10
<VALUE>:20
<DURATION_BONUS>:2
[/EFFECT]

#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES
<SFX>:STATIONARYTARGET:-1:0:0:0:SPELLS/EFFECTS/HASTE/haste.ams:0:1
<SFX>:FOLLOWTARGET:10:1:0:0:SPELLS/EFFECTS/REFLECT/reflect.ams:1:1
<SFX_DURATION_BONUS>:2
<SOUND>:SUCCESS:SOUNDS/SPELLS/charm.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast3.wav
<CAST_PARTICLE>:BLUESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:50
[/SPELL]

[SPELL]
<SPHERE>:DEFENSE
<NAME>:Fear
<TARGET_ALIGNMENT>:EVIL
<TARGET>:CHARACTER
<RANGE>:20
<CAST_TIME>:2
<MANA>:34
<ICON>:ICONS/spellfear.png:ICONS/spellfeara.png
<DESCRIPTION>:70% chance of causing a creature of level 5\nand below to flee the caster\n+1 creature level per Defense Skill Level

[EFFECT]
<CHANCE_OF_SUCCESS>:70
<ACTIVATION>:USAGE
<TYPE>:FLEE
<VALUE>:5
<VALUE_BONUS>:1
<DURATION>:INSTANT
<DAMAGE_TYPE>:MAGIC
<SFX>:FOLLOWTARGET:.5:1:0:0:SPELLS/EFFECTS/FIREPUFF/purplepuff.mdl:0:0
[/EFFECT]

#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:FOLLOWTARGET:.5:1:0:0:SPELLS/EFFECTS/FIREPUFF/purplepuff.mdl:0:0
<SOUND>:SUCCESS:SOUNDS/SPELLS/muffle.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast5.wav
<CAST_PARTICLE>:PURPLEFIRESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:37
[/SPELL]

[SPELL]
<SPHERE>:DEFENSE
<NAME>:Battle Fog
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:2
<MANA>:44
<ICON>:ICONS/spellbattlefog.png:ICONS/spellbattlefoga.png
<DESCRIPTION>:Increases Attack Rating by 100%\nand lowers Defense Rating by 25%\nfor 10 seconds\n+2 seconds of duration per Defense Skill level

[EFFECT]
<NAME>:BATTLEFOG
<EXCLUSIVE>:1
<MESSAGE>:Battle Fog!
<ACTIVATION>:USAGE
<TYPE>:PERCENTTOHITBONUS
<DURATION>:10
<VALUE>:100
<DURATION_BONUS>:2
[/EFFECT]

[EFFECT]
<NAME>:BATTLEFOGPENALTY
<EXCLUSIVE>:1
<ACTIVATION>:USAGE
<TYPE>:PERCENTARMORBONUS
<DURATION>:10
<VALUE>:-25
<DURATION_BONUS>:2
[/EFFECT]

#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES
<SFX>:FOLLOWTARGET:.5:1:0:0:SPELLS/EFFECTS/FIREPUFF/purplepuff.mdl:0:0
<SFX>:FOLLOWTARGET:10:1:0:0:SPELLS/EFFECTS/RINGS/redhalo.mdl:1:1
<SFX_DURATION_BONUS>:2
<SOUND>:SUCCESS:SOUNDS/SPELLS/charm.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast3.wav
<CAST_PARTICLE>:BLUESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:34
[/SPELL]

[SPELL]
<SPHERE>:DEFENSE
<NAME>:Dervish
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:2
<MANA>:50
<ICON>:ICONS/spelldervish.png:ICONS/spelldervisha.png
<DESCRIPTION>:Increases Attack Speed by 80%\nfor 10 seconds\n+2 seconds of duration per Defense Skill level

[EFFECT]
<NAME>:HASTEATTACK
<EXCLUSIVE>:1
<MESSAGE>:Dervish!
<ACTIVATION>:USAGE
<TYPE>:PERCENTATTACKSPEED
<DURATION>:10
<VALUE>:80
<DURATION_BONUS>:2
[/EFFECT]


#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES
<SFX>:FOLLOWTARGET:.5:1:0:0:SPELLS/EFFECTS/FIREPUFF/purplepuff.mdl:0:0
<SFX>:FOLLOWTARGET:10:1:0:0:SPELLS/EFFECTS/STAMINA/dervish.mdl:1:1
<SFX_DURATION_BONUS>:2
<SOUND>:SUCCESS:SOUNDS/SPELLS/charm.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast3.wav
<CAST_PARTICLE>:BLUESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:40
[/SPELL]

[SPELL]
<SPHERE>:DEFENSE
<NAME>:Resist Fire
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:2
<MANA>:25
<ICON>:ICONS/spellresistfire.png:ICONS/spellresistfirea.png
<DESCRIPTION>:Increases fire resistance to 75%\nfor 10 seconds\n+2 seconds of duration per Defense Skill level

[EFFECT]
<NAME>:RESISTFIRE
<EXCLUSIVE>:1
<MESSAGE>:Fire Resistance!
<ACTIVATION>:USAGE
<TYPE>:PERCENTFIRERESISTANCE
<DURATION>:10
<VALUE>:75
<DURATION_BONUS>:2
[/EFFECT]


#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES
<SFX>:FOLLOWTARGET:.5:1:0:0:SPELLS/EFFECTS/FIREPUFF/firepuff.mdl:0:0
<SFX>:FOLLOWTARGET:10:1:0:0:SPELLS/EFFECTS/RESIST/resistfire.ams:1:1
<SFX_DURATION_BONUS>:2
<SOUND>:SUCCESS:SOUNDS/SPELLS/charm.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast3.wav
<CAST_PARTICLE>:BLUESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:20
[/SPELL]

[SPELL]
<SPHERE>:DEFENSE
<NAME>:Resist Ice
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:2
<MANA>:25
<ICON>:ICONS/spellresistice.png:ICONS/spellresisticea.png
<DESCRIPTION>:Increases ice resistance to 75%\nfor 10 seconds\n+2 seconds of duration per Defense Skill level

[EFFECT]
<NAME>:RESISTICE
<EXCLUSIVE>:1
<MESSAGE>:Ice Resistance!
<ACTIVATION>:USAGE
<TYPE>:PERCENTICERESISTANCE
<DURATION>:10
<VALUE>:75
<DURATION_BONUS>:2
[/EFFECT]


#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES
<SFX>:FOLLOWTARGET:.5:1:0:0:SPELLS/EFFECTS/FIREPUFF/bluepuff.mdl:0:0
<SFX>:FOLLOWTARGET:10:1:0:0:SPELLS/EFFECTS/RESIST/resistice.ams:1:1
<SFX_DURATION_BONUS>:2
<SOUND>:SUCCESS:SOUNDS/SPELLS/charm.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast3.wav
<CAST_PARTICLE>:BLUESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:20
[/SPELL]

[SPELL]
<SPHERE>:DEFENSE
<NAME>:Resist Lightning
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:2
<MANA>:25
<ICON>:ICONS/spellresistlightning.png:ICONS/spellresistlightninga.png
<DESCRIPTION>:Increases electrical resistance to 75%\nfor 10 seconds\n+2 seconds of duration per Defense Skill level

[EFFECT]
<NAME>:RESISTLIGHTNING
<EXCLUSIVE>:1
<MESSAGE>:Lightning Resistance!
<ACTIVATION>:USAGE
<TYPE>:PERCENTELECTRICRESISTANCE
<DURATION>:10
<VALUE>:75
<DURATION_BONUS>:2
[/EFFECT]


#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES
<SFX>:FOLLOWTARGET:.5:1:0:0:SPELLS/EFFECTS/FIREPUFF/electricpuff.mdl:0:0
<SFX>:FOLLOWTARGET:10:1:0:0:SPELLS/EFFECTS/RESIST/resistlightning.ams:1:1
<SFX_DURATION_BONUS>:2
<SOUND>:SUCCESS:SOUNDS/SPELLS/charm.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast3.wav
<CAST_PARTICLE>:BLUESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:20
[/SPELL]

[SPELL]
<SPHERE>:DEFENSE
<NAME>:Greater Heal
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:2
<MANA>:50
<ICON>:ICONS/spellheal2.png:ICONS/spellheal2a.png
<DESCRIPTION>:Heals caster for 40 HP\n+3 HP per Defense Skill level

[EFFECT]
<ACTIVATION>:USAGE
<TYPE>:HPRECHARGE
<DURATION>:INSTANT
<VALUE>:40
<VALUE_BONUS>:3
[/EFFECT]

#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:FOLLOWTARGET:-1:0:0:0:SPELLS/EFFECTS/HEAL/heal.ams:0:1
<SOUND>:SUCCESS:SOUNDS/SPELLS/heal.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast.wav
<CAST_PARTICLE>:BLUESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0

<REQUIRES>:MAGIC:60
[/SPELL]

[SPELL]
<SPHERE>:DEFENSE
<NAME>:Greater Group Heal
<TARGET_ALIGNMENT>:ALL
<TARGET>:USERANDPETS
<CAST_TIME>:3
<MANA>:60
<ICON>:ICONS/spellgreatergroupheal.png:ICONS/spellgreatergroupheala.png
<DESCRIPTION>:Heals caster and minions for 24 HP\n+3 HP per Defense Skill level

[EFFECT]
<ACTIVATION>:USAGE
<TYPE>:HPRECHARGE
<DURATION>:INSTANT
<VALUE>:24
<VALUE_BONUS>:3
[/EFFECT]

#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:FOLLOWTARGET:-1:0:0:0:SPELLS/EFFECTS/HEAL/heal.ams:0:1
<SOUND>:SUCCESS:SOUNDS/SPELLS/heal.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast.wav
<CAST_PARTICLE>:BLUESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:65
[/SPELL]


[SPELL]
<SPHERE>:CHARM
<NAME>:Summon Zombies
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:3
<MANA>:20
<ICON>:ICONS/spellrat.png:ICONS/spellrata.png
<DESCRIPTION>:Summons 3 zombies to aid caster\n+1 to zombie's level per 2 Charm Skill levels\nDuration of summoning is 1 minute\n+10 seconds per Charm Skill Level\nMaximum of 6 summoned creatures

[EFFECT]
<NAME>:ZOMBIE
<ACTIVATION>:USAGE
<TYPE>:SUMMON
<DURATION>:INSTANT
<VALUE>:3
<VALUE2>:1
<VALUE2_BONUS>:.5
<VALUE3>:60
<VALUE3_BONUS>:10
#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:FOLLOWTARGET:1:1:0:0:SPELLS/EFFECTS/DISPEL/dispel.mdl:0:1
[/EFFECT]

<SOUND>:SUCCESS:SOUNDS/SPELLS/heal.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast.wav
<CAST_PARTICLE>:greenfirespark:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:24
[/SPELL]

[SPELL]
<SPHERE>:CHARM
<NAME>:Summon Mummies
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:3
<MANA>:20
<ICON>:ICONS/spellrat.png:ICONS/spellrata.png
<DESCRIPTION>:Summons 3 mummies to aid caster\n+1 to mummy's level per 2 Charm Skill levels\nDuration of summoning is 1 minute\n+10 seconds per Charm Skill Level\nMaximum of 6 summoned creatures

[EFFECT]
<NAME>:MUMMY
<ACTIVATION>:USAGE
<TYPE>:SUMMON
<DURATION>:INSTANT
<VALUE>:3
<VALUE2>:1
<VALUE2_BONUS>:.5
<VALUE3>:60
<VALUE3_BONUS>:10
#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:FOLLOWTARGET:1:1:0:0:SPELLS/EFFECTS/DISPEL/dispel.mdl:0:1
[/EFFECT]

<SOUND>:SUCCESS:SOUNDS/SPELLS/heal.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast.wav
<CAST_PARTICLE>:greenfirespark:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:30
[/SPELL]



[SPELL]
<SPHERE>:DEFENSE
<NAME>:Minor Heal Target
<TARGET_ALIGNMENT>:ALL
<TARGET>:CHARACTER
<CAST_TIME>:2
<MANA>:20
<ICON>:ICONS/spellheal.png:ICONS/spellheala.png
<DESCRIPTION>:Heals target for 10 HP\n+2 HP per Defense Skill level

[EFFECT]
<ACTIVATION>:USAGE
<TYPE>:HPRECHARGE
<DURATION>:INSTANT
<VALUE>:10
<VALUE_BONUS>:2
[/EFFECT]

#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:FOLLOWTARGET:-1:0:0:0:SPELLS/EFFECTS/HEAL/heal.ams:0:1
<SOUND>:SUCCESS:SOUNDS/SPELLS/heal.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast.wav
<CAST_PARTICLE>:BLUESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
[/SPELL]


[SPELL]
<SPHERE>:CHARM
<NAME>:Banish
<TARGET_ALIGNMENT>:EVIL
<TARGET>:CHARACTER
<CAST_TIME>:3
<MANA>:40
<ICON>:ICONS/spelldispel.png:ICONS/spelldispela.png
<DESCRIPTION>:Dispel target's summoned creatures

[EFFECT]
<NAME>:DISPEL
<EXCLUSIVE>:1
<ACTIVATION>:USAGE
<TYPE>:DISPEL
<MESSAGE>:Summons Banished!
[/EFFECT]


#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES
<SFX>:FOLLOWTARGET:1:1:0:0:SPELLS/EFFECTS/DISPEL/dispel.mdl:0:1
<SOUND>:SUCCESS:SOUNDS/SPELLS/charm.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast3.wav
<CAST_PARTICLE>:REDFIRESPARK:0:0:0
<CAST_PARTICLE>:PURPLEFIRESPARK:0:0:0
<REQUIRES>:MAGIC:20
[/SPELL]


#################################################
# DUMMY SPELLS TO PROVIDE DURATION ICONS FOR ATTACK EFFECTS
#################################################

[SPELL]
<SPHERE>:ATTACK
<NAME>:Poison
<TARGET_ALIGNMENT>:EVIL
<TARGET>:USERAREA
<RANGE>:0
<CAST_TIME>:2000
<MANA>:60000
<ICON>:ICONS/spellpoison.png:ICONS/spellpoisona.png
<DESCRIPTION>:Poisons all hostile targets within 20 feet.\nPoison duration is 20 seconds\n2 points of damage per second\n+2 seconds per Attack Skill level

[EFFECT]
<NAME>:POISON
<EXCLUSIVE>:1
<ACTIVATION>:USAGE
<TYPE>:HPRECHARGE
<DURATION>:20
<VALUE>:-120
<DURATION_BONUS>:2
<DAMAGE_TYPE>:MAGIC
<CHANCE_OF_SUCCESS>:100
[/EFFECT]

#SFX:TYPE:DURATION:LOOPING:SPEED:TURNRATE:PATH TO EFFECT:EXCLUSIVE:RESPECT BONUSES

<SFX>:STATIONARYOWNER:2:1:0:0:SPELLS/EFFECTS/POISONCLOUD/poisoncloud.mdl:0:1
<SOUND>:SUCCESS:SOUNDS/FX/poison2.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast4.wav
<CAST_PARTICLE>:GREENFIRESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:9999999
[/SPELL]

#Bonus Pack Spell

[SPELL]
<SPHERE>:CHARM
<NAME>:Summon Demonling
<TARGET_ALIGNMENT>:ALL
<TARGET>:USER
<CAST_TIME>:2
<MANA>:35
<ICON>:ICONS/spellbats.png:ICONS/spellbatsa.png
<DESCRIPTION>:Summons 3 level 10 Devilkins to aid caster\n+1 to Devilkins' level per 3 Charm Skill levels\nDuration of summoning is 1 minute\n+10 seconds per Charm Skill Level\nMaximum of 6 summoned creatures
<SOUND>:SUCCESS:SOUNDS/SPELLS/heal.wav
<SOUND>:FAIL:SOUNDS/SPELLS/fail.wav
<SOUND>:CHANT:SOUNDS/SPELLS/cast.wav
<CAST_PARTICLE>:GREENFIRESPARK:0:0:0
<CAST_PARTICLE>:TINYFASTGLEAM:0:0:0
<REQUIRES>:MAGIC:35

[EFFECT]
<NAME>:Demonling
<ACTIVATION>:USAGE
<TYPE>:SUMMON
<DURATION>:INSTANT
<VALUE>:3
<VALUE2>:10
<VALUE2_BONUS>:.3333
<VALUE3>:60
<VALUE3_BONUS>:10
<SFX>:FOLLOWTARGET:1:1:0:0:SPELLS/EFFECTS/DISPEL/dispel.mdl:0:0
[/EFFECT]
[/SPELL]

#################################################
# END OF FILE
#################################################
